# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - uses: actions/checkout@v4

    # Step 2: Set up Python 3.10
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    # Step 3: Set up Google credentials (from GitHub secrets)
    - name: Set up Google credentials
      run: |
        echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}" > $HOME/google-credentials.json
        export GOOGLE_APPLICATION_CREDENTIALS=$HOME/google-credentials.json

    # Step 4: Set environment variables from GitHub secrets
    - name: Set environment variables
      env:
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        DATASET_ID: ${{ secrets.DATASET_ID }}
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      run: |
        echo "PROJECT_ID: $PROJECT_ID"
        echo "DATASET_ID: $DATASET_ID"
        echo "GOOGLE_API_KEY: $GOOGLE_API_KEY"

    # Step 5: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Step 6: Lint with flake8
    - name: Lint with flake8
      run: |
        # Run flake8 with default settings to check for syntax errors, undefined names, etc.
        flake8 .
    # Step 7: Build and Push Docker Image
    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: kianahs/ai-powered-product-review-sentiment-analysis
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
